const supabaseUrl = "https://kytlboobxypxkuaesorc.supabase.co";
const supabaseKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dGxib29ieHlweGt1YWVzb3JjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNDYyMTY0MCwiZXhwIjoyMDMwMTk3NjQwfQ.B6UaLEkld-fWPhVKsxvrMN4H-NC43VMd5VHYUjRfni8';
