name: rekam_medis_redis
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  multi_select_search: ^0.0.3
  flutter_typeahead: ^4.3.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  multi_select_flutter: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
